[logger]
level = "info"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false
port = 8501
maxUploadSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
